config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'about', to: 'pages#about'

  resources :coffee_shops
  resources :customers
  resources :reviews

  # Define the root route
  root 'pages#about#index'
end

app/models/coffee_shop.rb
class CoffeeShop < ApplicationRecord
  # A coffee shop can have many reviews (one-to-many)1.5
 has_many :reviews
 # A coffee shop can have many reviews (1 to many) 1.4
  # A coffee shop can have many customers through reviews (many-to-many) 1.5
 has_many :customers, through: :reviews

  # A coffee shop can have many customers as their favorite coffee shop
 has_many :favorited_by_customers, class_name: 'Customer', foreign_key: 'favorite_coffee_shop_id'

 #1.6 validations
 # Name must be present and unique
 validates :name, presence: true, uniqueness: true

 # Location must be present
 validates :location, presence: true

 # Rating must be present and a number between 0 and 5
 validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

 # Description must be present and at least 10 characters long
 validates :description, presence: true, length: { minimum: 10 }




 #3.5
 paginates_per 10

 #4.2
 before_save :format_rating

 private

  def format_rating
    self.rating = rating.round(1)
  end
end

app/controllers/coffee_shops_controller.rb
class CoffeeShopsController < ApplicationController
  before_action :set_coffee_shop, only: %i[ show edit update destroy ]

  # GET /coffee_shops or /coffee_shops.json
  def index
    @rating_filter = params[:rating_filter]
    @keyword = params[:keyword]

    @coffee_shops = CoffeeShop.all

    if @rating_filter.present?
      case @rating_filter
      when "1-2"
        @coffee_shops = @coffee_shops.where(rating: 1.0..2.0)
      when "3-4"
        @coffee_shops = @coffee_shops.where(rating: 3.0..4.0)
      when "4-5"
        @coffee_shops = @coffee_shops.where(rating: 4.0..5.0)
      end
    end

    if @keyword.present?
      @coffee_shops = @coffee_shops.where("name LIKE ?", "%#{@keyword}%")
    end

    @coffee_shops = @coffee_shops.page(params[:page])
  end

  # GET /coffee_shops/1 or /coffee_shops/1.json
  def show
  end

  # GET /coffee_shops/new
  def new
    @coffee_shop = CoffeeShop.new
  end

  # GET /coffee_shops/1/edit
  def edit
  end

  # POST /coffee_shops or /coffee_shops.json
  def create
    @coffee_shop = CoffeeShop.new(coffee_shop_params)

    respond_to do |format|
      if @coffee_shop.save
        format.html { redirect_to coffee_shop_url(@coffee_shop), notice: "Coffee shop was successfully created." }
        format.json { render :show, status: :created, location: @coffee_shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coffee_shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_shops/1 or /coffee_shops/1.json
  def update
    respond_to do |format|
      if @coffee_shop.update(coffee_shop_params)
        format.html { redirect_to coffee_shop_url(@coffee_shop), notice: "Coffee shop was successfully updated." }
        format.json { render :show, status: :ok, location: @coffee_shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coffee_shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_shops/1 or /coffee_shops/1.json
  def destroy
    @coffee_shop.destroy

    respond_to do |format|
      format.html { redirect_to coffee_shops_url, notice: "Coffee shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_shop
      @coffee_shop = CoffeeShop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_shop_params
      params.require(:coffee_shop).permit(:name, :location, :rating, :description)
    end
end

app/helpers/coffee_shops_helper.rb
module CoffeeShopsHelper
end

app/views/coffee_shops/_form.html.erb
<%= form_with(model: coffee_shop) do |form| %>
  <% if coffee_shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffee_shop.errors.count, "error") %> prohibited this coffee_shop from being saved:</h2>

      <ul>
        <% coffee_shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coffee_shops/edit.html.erb
<h1>Editing Coffee Shop</h1>

<%= render 'form', coffee_shop: @coffee_shop %>

<%= link_to 'Show', @coffee_shop %> |
<%= link_to 'Back', coffee_shops_path %>

app/views/coffee_shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffee Shops</h1>

<%= form_with url: coffee_shops_path, method: :get, local: true do %>
  <%= label_tag :keyword, "Search:" %>
  <%= text_field_tag :keyword, @keyword %>
  <%= label_tag :rating_filter, "Filter by Rating:" %>
  <%= select_tag :rating_filter, options_for_select([["All", ""], ["1-2", "1-2"], ["3-4", "3-4"], ["4-5", "4-5"]], selected: @rating_filter) %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Rating</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffee_shops.each do |coffee_shop| %>
      <tr>
        <td><%= coffee_shop.name %></td>
        <td><%= coffee_shop.location %></td>
        <td><%= coffee_shop.rating %></td>
        <td><%= coffee_shop.description %></td>
        <td><%= link_to 'Show', coffee_shop %></td>
        <td><%= link_to 'Edit', edit_coffee_shop_path(coffee_shop) %></td>
        <td><%= link_to 'Destroy', coffee_shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @coffee_shops %>


<br>

<%= link_to 'New Coffee Shop', new_coffee_shop_path %>

app/views/coffee_shops/new.html.erb
<h1>New Coffee Shop</h1>

<%= render 'form', coffee_shop: @coffee_shop %>

<%= link_to 'Back', coffee_shops_path %>

app/views/coffee_shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coffee_shop.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @coffee_shop.location %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @coffee_shop.rating %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coffee_shop.description %>
</p>

<h2>Reviews:</h2>
<% @coffee_shop.reviews.each do |review| %>
  <p><%= review.customer.first_name %> <%= review.customer.last_name %>: <%= review.comment %> (Rating: <%= review.rating %>)</p>
<% end %>

<%= link_to 'Edit', edit_coffee_shop_path(@coffee_shop) %> |
<%= link_to 'Back', coffee_shops_path %>