config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'about', to: 'pages#about'

  resources :coffee_shops
  resources :customers
  resources :reviews

  # Define the root route
  root 'pages#about#index'
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :favorite_coffee_shop, class_name: 'CoffeeShop', optional: true
   # A customer can have many reviews (one-to-many) 1.5
  has_many :reviews
   # A customer can have many reviewed coffee shops through reviews (many-to-many) 1.5
  has_many :reviewed_coffee_shops, through: :reviews, source: :coffee_shop

  #1.6 validations
 # First name must be present and at least 2 characters long
 validates :first_name, presence: true, length: { minimum: 2 }

 # Last name must be present and at least 2 characters long
 validates :last_name, presence: true, length: { minimum: 2 }

 # Email must be present, unique, and follow a valid email format
 validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

 #3.5
 paginates_per 10
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.page(params[:page])
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :favorite_coffee_shop_id)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :favorite_coffee_shop_id %>
    <%= form.text_field :favorite_coffee_shop_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Favorite coffee shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.favorite_coffee_shop_id %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @customers %>
<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Favorite coffee shop:</strong>
  <%= @customer.favorite_coffee_shop_id %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>